version: "3"
services:
  selenium:
    image: selenium/standalone-chrome
    ports: 
      - 4444:4444
  uniqgo:
    image: golang:1.6.1-alpine
    volumes:
      - .:/go/uniqgo
    working_dir: /go/uniqgo
    command: cmd/uniqgo
